### ISSUE TITLE
[BUG] Не отображаются значки (кнопки)

### ISSUE THREAD

**Issue by Oleg720** [anilibria/anilibria-win#36]
**Страница приложения/Application page**
- Домашняя страница(содержит sidebar)/Home page(contains sidebar)

**Описание ошибки/Describe the bug**
Не отображаются иконки

**Для воспроизведения/To Reproduce**
Они изначально не отображаются

**Скриншоты/Screenshots**
![img1]
![img2]

**Сведения о системе <> (please complete the following information):**
 - Версия Windows 10/Windows 10 version: 1809
 - Размер экрана/Screen size: 1600x900
 - Версия приложения/Application Version: 0.1.14
- Объем оперативной памяти/RAM size: 6GB

**Дополнительные данные/Additional context**
Перезапуск не помогает
Ошибка происходит вне зависимости от того, авторизован или нет
Хоть кнопки и невидимы, но кликабельны

[img1]: https://i.imgur.com/nIKlAe9.png
[img2]: https://i.imgur.com/GidCjD4.png

**Comment by trueromanus** [comment]
Можно попросить ответить на следующие вопросы:
- Работает ли устройство от сети или нет? Если второе то какой режим энергообеспечения включен.
- Помогает ли изменение размеров окна и/или минимизация/максимизация?
- Откуда было установлено приложение wstore/web/offline ?

**Comment by Oleg720** [comment]
- Вне зависимости от питания по сети или от батареи, а также вне зависимости от режима энергопотребления - ошибка есть всегда.
- Изменение размеров окна не помогает
- Приложение установлено из WStore

**Comment by trueromanus** [comment]
Я не смог повторить на своей стороне поэтому я подготовил специальное приложение чтобы понять какая версия рисования иконки будет работать на Вашей машине. Убедительная просьба установить это приложение и снять скриншот окна этого приложения и выложить сюда. Заранее спасибо за кооперацию и потраченное на решение этой проблемы время.

Для установки вначале включите sideloading (В настройках -> Обновление и Безопасность -> Для разработчиков и смените режим на Неопубликованные приложения/Sideloading), скачайте архив W10Exp_1.0.5.0_Test.zip [отсюда ](https://github.com/anilibria/anilibria-win/releases/tag/exp105), распакуйте и запустите с помощью Powershell файл Add-AppDevPackage.ps1(правой кнопкой - пункт Запустить с Powershell). После этого Вам предложат запуститься с админскими правами и установить сертификат (спокойно, потом его удалим просто иначе это не будет работать). Дождаться пока оно установится и потом найти приложение с именем W10Exp.

После снятия скриншота удалите сертификат (он будет в Корневые центры сертификации):
![cert](https://user-images.githubusercontent.com/9040186/57011702-ac242200-6c0b-11e9-9b7b-b76b186a93b2.png)
После чего удалите приложение.

**Comment by Oleg720** [comment]
![img]

[img]: https://i.imgur.com/bnF5ckS.png

**Comment by trueromanus** [comment]
Войдет в версию 0.1.16
