### ISSUE TITLE
[FEATURE] New branch for landing page

### ISSUE THREAD

**Issue by AppLoidx** [anilibria/anilibria-win#45]
**Если предложение относиться к какой-то проблеме опишите её.**
Не то чтобы это проблема, но было бы удобно иметь отдельную ветку для лэндинг-страницы. Сейчас, есть index.html и index.css с простым дизайном, но если решить его расширить, как например, здесь https://github.com/anilibria/anilibria-win/pull/44 , то веб-страница перемешается с приложением, что не совсем удобно.

**Опишите предлагаемое Вами решение проблемы**
Я предлагаю сделать отдельную ветку `gh-pages` и настроить GitHub pages находить файлы не из `master` ветки, а из `gh-pages`. В свою очередь из `gh-pages` нужно будет удалить все исходники самого приложения (С#)

**Comment by AppLoidx** [comment]
Например, вот так : https://github.com/AppLoidx/anilibria-win/tree/gh-pages

**Comment by trueromanus** [comment]
На githubpages в этом репозитории выкладывается инсталляторы и дистрибутивы для авто-обновления приложения поэтому заводить отдельную ветку и положить туда только страничку с лендингом не вижу смысла. Но за клевую страничку приложения спасибо :thumbsup:.

**Comment by AppLoidx** [comment]
Всегда пожалуйста! Хоть что-то сделаю для аниме-индустрии (косвенно хотя бы 😉)
