### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by mishailovic** [anilibria/anilibria-win#46]
Пацанчики, а что версии для красноглазиков не будет? Сижу на linux, как то грустно стало

**Comment by trueromanus** [comment]
Версия для красноглазиков в процессе разработки в стадии prealpha.
Если не терпится то можете (заодно проверить как оно там у Вас) собрать из исходников. На линухе требуется наличие иксов или кед а также qmake и qt 5.12. После клонирования репозитория файл проекта .pro находиться в папке srcnport/AniLibria.
Ну а если не хочется эксперементировать то стоит подождать.
