### ISSUE TITLE
Добавить кнопку ускорения x1.5

### ISSUE THREAD

**Issue by MISTikus** [anilibria/anilibria-win#49]
На сайте смотрю релизы на скорости 1,5, считаю ее более чем комфортной для просмотра и восприятия контента, однако в приложении минимальное ускорение x2

Как на счет добавить (или заменить одну из кнопок) ускорение x1.5?

З.Ы. к.м.к. удобными режимами ускорения (не перемотки) были бы (как и на сайте) 1.25, 1.5 и 2

**Comment by trueromanus** [comment]
Изменение войдет в версию 1.0.13
