### ISSUE TITLE
[BUG] Неподдерживаемый тип видео

### ISSUE THREAD

**Issue by MISTikus** [anilibria/anilibria-win#50]
**Укажите страницу приложения/Specify application page**
- Список релизов/Release's page

**Описание ошибки/Describe the bug**
Периодически отваливаются разные релизы с текстом:
`Ошибка: неподдерживаемый тип видео или недопустимый путь к файлу`

**Для воспроизведения/To Reproduce**
БД: [ссылка](https://cloud.mail.ru/public/4cbX%2F3uiyatsri)
Сейчас повторяется на релизе "Боруто"

**Ожидаемое поведение/Expected behavior**
Отсутствие ошибки

**Скриншоты/Screenshots**
[Скриншот](https://cloud.mail.ru/public/4cSJ%2F3R3WYtvot)
[Гифка](https://cloud.mail.ru/public/3ck1%2F2KpnQ7na2)

**Сведения о системе <> (please complete the following information):**
 - Версия Windows 10/Windows 10 version: 20H2
 - Размер экрана/Screen size: 1920х1080
 - Версия приложения/Application Version: 1.0.16
- Объем оперативной памяти/RAM size: 16гб

**Comment by trueromanus** [comment]
Проблемы не в приложении а на стороне серверов. Ответственные за это уже решают проблему.

**Comment by MISTikus** [comment]
> Проблемы не в приложении а на стороне серверов. Ответственные за это уже решают проблему.

а почему тогда помогает сброс бд?

*т.е. после удаления бд баг не повторяется с этим же релизом

**Comment by trueromanus** [comment]
Вероятно потому что после синхронизации адрес видео меняется со стороны серверов, после чего все работает:) Бывает надо просто выполнить синхронизацию несколько раз чтобы обновились адреса видео. Адресов с видео может быть много, бывает что попадает на сервер-кеш который не работает или он выбирается специально я хз. Приложение просто читает адреса с сайта и пытается скачать их во время воспроизведения, если не удается это сделать то выдается вышеупомянутое сообщение.
