### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KotNaKiske** [anilibria/anilibria-win#51]
не устанавливается виндовс приложение у вас сертификат кончился в 06 месяце.. обновите

**Comment by trueromanus** [comment]
В версии 1.0.18 сертификат закончиться 05.03.2022.
![image](https://user-images.githubusercontent.com/9040186/126907709-8f1c7765-6993-49bc-b73c-2f6317ed7f71.png)

**Comment by trueromanus** [comment]
Все понятно баг связан только с онлайн установкой. Ставьте с использованием оффлайн (и ныне единственной версией). 
Вот на этой [страничке](https://github.com/anilibria/anilibria-win/releases/tag/1.0.18) есть архив Anilibria_1.0.18.0_Test.zip с приложением а также ссылки на инструкции как поставить само приложение и сертификат если сам установщик не справится.

**Comment by KotNaKiske** [comment]
+ получилось.
