### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by goodgeet7300** [anilibria/anilibria-win#52]
При попытке установки сертификата через install.ps1 файл вылезает эта ошибка и не даёт установить приложение. Как с этим бороться?
![image](https://user-images.githubusercontent.com/26352129/173362449-925d7f73-92e4-42ed-9481-65520a2afc86.png)

З.Ы. Режим разработчика и выполнение локальных скриптов включены

**Comment by trueromanus** [comment]
Здравствуйте, данное приложение не поддерживается.
Подробности читайте в разделе [Важное объявление](https://github.com/anilibria/anilibria-win#%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5).
Актуальное на текущий момент приложение можно найти [тут](https://github.com/anilibria/anilibria-winmaclinux#anilibriaqt).
